apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: homepage

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - secret.yaml
  - bitwardensecret.yaml
  - clusterrole_clusterrolebinding.yaml
  - service.yaml
  - deployment.yaml
  - httproute.yaml

configMapGenerator:
  - name: homepage
    files:
      - config/custom.js
      - config/custom.css
      - config/bookmarks.yaml
      - config/docker.yaml
      - config/kubernetes.yaml
      - config/services.yaml
      - config/settings.yaml
      - config/widgets.yaml
