- Hypervisor:
    - Frostmourne::
        icon: proxmox.svg
        href: "{{HOMEPAGE_VAR_FROSTMOURNE_URL}}"
        description: Proxmox-UniqueSSL
        widget:
            type: proxmox
            url: "{{HOMEPAGE_VAR_FROSTMOURNE_URL}}"
            username: "{{HOMEPAGE_VAR_FROSTMOURNE_USER}}"
            password: "{{HOMEPAGE_VAR_FROSTMOURNE_APIKEY}}"
- Shalamayne:
    - CPU Usage:
        widget:
            type: glances
            url: "{{HOMEPAGE_VAR_SHALAMAYNE_URL}}"
            username: "{{HOMEPAGE_VAR_SHALAMAYNE_USER}}" # optional if auth enabled in Glances
            password: "{{HOMEPAGE_VAR_SHALAMAYNE_APIKEY}}" # optional if auth enabled in Glances
            version: 4 # required only if running glances v4 or higher, defaults to 3
            metric: cpu
            refreshInterval: 5000 # optional - in milliseconds, defaults to 1000 or more, depending on the metric
            pointsLimit: 15 # optional, defaults to 15
            chart: false
    - GPU Usage:
        widget:
            type: glances
            url: "{{HOMEPAGE_VAR_SHALAMAYNE_URL}}"
            username: "{{HOMEPAGE_VAR_SHALAMAYNE_USER}}" # optional if auth enabled in Glances
            password: "{{HOMEPAGE_VAR_SHALAMAYNE_APIKEY}}" # optional if auth enabled in Glances
            version: 4
            metric: gpu:nvidia0        
    - Memory Usage:
        widget:
            type: glances
            url: "{{HOMEPAGE_VAR_SHALAMAYNE_URL}}"
            username: "{{HOMEPAGE_VAR_SHALAMAYNE_USER}}" # optional if auth enabled in Glances
            password: "{{HOMEPAGE_VAR_SHALAMAYNE_APIKEY}}" # optional if auth enabled in Glances
            version: 4 # required only if running glances v4 or higher, defaults to 3
            metric: memory
            chart: false
    -  Network Usage:
        widget:
            type: glances
            url: "{{HOMEPAGE_VAR_SHALAMAYNE_URL}}"
            username: "{{HOMEPAGE_VAR_SHALAMAYNE_USER}}" # optional if auth enabled in Glances
            password: "{{HOMEPAGE_VAR_SHALAMAYNE_APIKEY}}" # optional if auth enabled in Glances
            version: 4 # required only if running glances v4 or higher, defaults to 3
            metric: network:enp5s0
            chart: false
    - Top Processes:
        widget:
            type: glances
            url: "{{HOMEPAGE_VAR_SHALAMAYNE_URL}}"
            username: "{{HOMEPAGE_VAR_SHALAMAYNE_USER}}" # optional if auth enabled in Glances
            password: "{{HOMEPAGE_VAR_SHALAMAYNE_APIKEY}}" # optional if auth enabled in Glances
            version: 4 # required only if running glances v4 or higher, defaults to 3
            metric: process
    - Disk I/O:
        widget:
            type: glances
            url: "{{HOMEPAGE_VAR_SHALAMAYNE_URL}}"
            username: "{{HOMEPAGE_VAR_SHALAMAYNE_USER}}" # optional if auth enabled in Glances
            password: "{{HOMEPAGE_VAR_SHALAMAYNE_APIKEY}}" # optional if auth enabled in Glances
            version: 4 # required only if running glances v4 or higher, defaults to 3
            metric: disk:nvme0n1
            chart: false
- Network:
    - UniFi:
        icon: unifi.svg
        href: https://malfurion.zeroenet.cloud
        description: network-WildcardSSL
        widget:
            type: unifi
            url: https://10.28.28.1
            username:  "{{HOMEPAGE_VAR_UNIFI_USER}}"
            password:  "{{HOMEPAGE_VAR_UNIFI_APIKEY}}"
    - Nginx Proxy Manager:
        icon: nginx-proxy-manager.svg
        href: https://proxy.zeroenet.cloud
        description: internal proxy-RP
        widget:
            type: npm
            url: https://proxy.zeroenet.cloud
            username: "{{HOMEPAGE_VAR_NGINXPM_USER}}"
            password: "{{HOMEPAGE_VAR_NGINXPM_APIKEY}}" 
    - Traefik:
        icon: traefik-proxy.svg
        href: https://traefik.zeroenet.cloud
        description: kubernetes gateway
        namespace: traefik
        app: traefik
        widget:
            type: traefik
            url: https://traefik.zeroenet.cloud
            username: "{{HOMEPAGE_VAR_TRAEFIK_USER}}"
            password: "{{HOMEPAGE_VAR_TRAEFIK_PASSWORD}}"

- DNS:
    - PiHole:
        icon: pi-hole.svg
        href: "{{HOMEPAGE_VAR_PIHOLE_URL_ADMIN}}"
        description: DNS 
        widget:
            type: pihole
            url: "{{HOMEPAGE_VAR_PIHOLE_URL}}"
            version: 6 # required if running v6 or higher, defaults to 5
            key: "{{HOMEPAGE_VAR_PIHOLE_APIKEY}}" # optional, in v6 can be your password or app password
    - Backup-PiHole:
        icon: pi-hole.svg
        href: "{{HOMEPAGE_VAR_BACKUP_PIHOLE_URL_ADMIN}}"
        description: Backup DNS
        widget:
            type: pihole
            url:  "{{HOMEPAGE_VAR_BACKUP_PIHOLE_URL}}"
            version: 6
            key: "{{HOMEPAGE_VAR_BACKUP_PIHOLE_APIKEY}}"

- Monitors:
    - Status:
        icon: uptime-kuma.svg
        href: https://status.zeroenet.cloud
        description: Primary Uptime Monitor
        namespace: uptimekuma
        app: uptime-kuma
        widget:
            type: uptimekuma
            url: https://status.zeroenet.cloud
            slug: uptime-zeroenet
    - Overwatch:
        icon: uptime-kuma.svg
        href: https://overwatch.zeroenet.cloud
        description: Backup Uptime Monitor
        widget:
            type: uptimekuma
            url: https://overwatch.zeroenet.cloud
            slug: overwatch-zeroenet
    - PeaNUT:
        icon: peanut.svg
        href: https://peanut.zeroenet.cloud
        description: UPS monitor
        namespace: peanut
        app: peanut
        widget:
            type: customapi
            url: https://peanut.zeroenet.cloud/api/v1/devices/ups
            mappings:
              - field: battery.charge
                label: Battery Charge
                format: percent
              - field: battery.runtime
                label: Battery Runtime
                format: duration
              - field: ups.load
                label: UPS Load
                format: percent
              - field: ups.status
                label: UPS Status
                format: text
                remap:
                  - value: OL
                    to: Online
                  - value: OB
                    to: On Battery
                  - value: LB
                    to: Low Battery
                  - any: true
                    to: Unknown

- Authentication:
    - Authentik:
        icon: authentik.svg
        href: "{{HOMEPAGE_VAR_AUTHENTIK_URL}}"
        description: SSO for user apps
        widget:
            type: authentik
            url: "{{HOMEPAGE_VAR_AUTHENTIK_URL}}"
            key: "{{HOMEPAGE_VAR_AUTHENTIK_TOKEN}}"
            version: 2
- CI/CD:
    - Argo CD:
        icon: argocd.svg
        href: "{{HOMEPAGE_VAR_ARGOCD_URL}}"
        description: automate k8s app deployment
        widget:
            type: argocd
            url: "{{HOMEPAGE_VAR_ARGOCD_URL}}"
            key: "{{HOMEPAGE_VAR_ARGOCD_TOKEN}}"

- Media:
    - Home-Plex:
        icon: plex.svg
        href: "{{HOMEPAGE_VAR_PLEX_URL}}"
        description: Plex
        widget:
            type: plex
            url: "{{HOMEPAGE_VAR_PLEX_URL}}"
            key: "{{HOMEPAGE_VAR_PLEX_APIKEY}}"
    - Seerr:
        icon: jellyseerr.svg
        href: "{{HOMEPAGE_VAR_SEERR_URL}}"
        description: Media requests
        namespace: seerr
        app: seerr-chart
        widget:
            type: jellyseerr
            url: "{{HOMEPAGE_VAR_SEERR_URL}}"
            key: "{{HOMEPAGE_VAR_SEERR_APIKEY}}"
    - qBittorrent:
        icon: qbittorrent.svg
        href: https://mailman.zeroenet.cloud
        description: Mailman-RP
        widget:
            type: qbittorrent
            url: https://mailman.zeroenet.cloud
            username: "{{HOMEPAGE_VAR_QBIT_USER}}"
            password: "{{HOMEPAGE_VAR_QBIT_APIKEY}}"
    - Prowlarr:
        icon: prowlarr.svg
        href: https://prowlarr.zeroenet.cloud
        description: Indexer-RP
        widget:
            type: prowlarr
            url: https://prowlarr.zeroenet.cloud
            key: "{{HOMEPAGE_VAR_PRWLR_APIKEY}}"

    - Radarr:
        icon: radarr.svg
        href: https://radarr.zeroenet.cloud
        description: Movies-RP
        widget:
            type: radarr
            url: https://radarr.zeroenet.cloud
            key: "{{HOMEPAGE_VAR_RDR_APIKEY}}"
    - Sonarr:
        icon: sonarr.svg
        href: https://sonarr.zeroenet.cloud
        description: TV Shows-RP
        widget:
            type: sonarr
            url: https://sonarr.zeroenet.cloud
            key: "{{HOMEPAGE_VAR_SNR_APIKEY}}" 