- kubernetes:
    cluster:
      show: true
      cpu: true
      memory: true
      showLabel: true
      label: "zeroenet-cluster"
    nodes:
      show: true
      cpu: true
      memory: true
      showLabel: true
- resources:
    backend: resources
    expanded: true
    network: default
- longhorn:
    href: https://longhorn.zeroenet.cloud
    expanded: true
    total: true
    labels: true
    nodes: true
# - search:
#     provider: google
#     target: _blank
- datetime:
    text_size: xl
    format:
      timeStyle: short
      hourCycle: h23
      dateStyle: long
- openmeteo:
    label: "{{HOMEPAGE_VAR_LOCATION}}" # optional
    latitude: {{HOMEPAGE_VAR_LAT}}
    longitude: {{HOMEPAGE_VAR_LON}}
    timezone: "{{HOMEPAGE_VAR_TIMEZ}}" # optional
    units: imperial # or imperial
    cache: 5 # Time in minutes to cache API responses, to stay within limits
    format: # optional, Intl.NumberFormat options
      maximumFractionDigits: 1