apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Add prod-specific overrides here later, e.g., replicas, resources, hostnames
patchesStrategicMerge:
  # - deployment-patch.yaml